### ISSUE TITLE
Authorization fails when using headers option

### ISSUE THREAD

**Issue by creage** [SamDecrock/node-http-ntlm#108]
Our NTLM authorization fails when `headers` option is used.

We are using `httpntlm` as an NTLM proxy, thus we need all of headers coming with original request to be passed down to the target server.

```js
const http = require('http');
const httpntlm = require('httpntlm');

const server = http.createServer(function (request, response) {
    const ntlmOptions = {
        // ... NTLM options here, and
        headers: request.headers // pass original request headers
    };

    httpntlm[request.method](ntlmOptions, (err, res) => {
        // ... process the response
    });
}).listen(8006);
```

This code used to work until v1.8.10. That commit https://github.com/SamDecrock/node-http-ntlm/commit/f2c71c9a8cc956685b957bb993c601dfdceff245 changed the behavior, so now our NTLM server returns 401 for all requests.

**Comment by SamDecrock** [comment]
Weird, not much changed TBH. I reverted something in httpntlm@1.8.13
Can you try the latest version?

**Comment by creage** [comment]
@SamDecrock it works now, thanks!
