### ISSUE TITLE
Getting 401 Unauthorized with username containing '\n'

### ISSUE THREAD

**Issue by lejlabe** [SamDecrock/node-http-ntlm#109]
I'm using the httpntlm library as per example https://github.com/SamDecrock/node-http-ntlm#use-the-ntlm-functions-yourself. In my case, username contains character '\N' and options for `ntlm.createType3Message` call are sent in this format:
`var options={
  url,
  username: "EXAMPLE\\NUSER",
  password,
  workstation,
  domain,
};`

However, call is failing with error 401 Unauthorized. I've tried to pass the username as "EXAMPLE\NUSER" and "EXAMPLE\\\\NUSER", but result is the same. When I'm using different credentials - authorization is successful. 
Are there any limitations of this library when username contains special characters or am I making some obvious mistake?

Thanks

**Comment by capc0** [comment]
@lejlabe did you resolve this issue? :)

Edit: updating from 1.7.7 to 1.8.13 fixed the issue for me.

---

Providing a custom http agent with `maxSockets: 1` fixed another issue regarding 401 responses
