### ISSUE TITLE
Protocol "https:" not supported. Expected "http:".

### ISSUE THREAD

**Issue by DaleCox** [SamDecrock/node-http-ntlm#25]
When redirecting via a 302 from http to https (to authenticate) the following error occurs

Uncaught Error: Protocol "https:" not supported. Expected "http:".
 at new ClientRequest (_http_client.js:75:11)
 at Object.exports.request (http.js:49:10)
 at Object.exports.request (https.js:136:15)
 at _stream_readable.js:908:16

Now I understand we normally don’t want to pass credentials in the clear but the use case I’m trying to support is when a developer is coding locally and needs to make authenticated web service calls to that local code

**Comment by adamvresky** [comment]
Same problem here.

**Comment by hhellbusch** [comment]
Ran into this as well.

**Comment by SamDecrock** [comment]
Let me know if the fix works!
