### ISSUE TITLE
Requiring node v0.11

### ISSUE THREAD

**Issue by kjvalencik** [SamDecrock/node-http-ntlm#26]
In https://github.com/SamDecrock/node-http-ntlm/commit/c229d602d386fff137598ff8d477c15f03ac7dc3 you switched the engine version to `>=0.11.0`. It appears to work fine in `v0.10.38`. Is this just an oversight or am I missing some dependency that requires a newer version?

Thanks!

@cphoover

**Comment by SamDecrock** [comment]
I'm now using the built-in https.Agent so I'm lowering the version again.
