### ISSUE TITLE
Not working - bind must be completed

### ISSUE THREAD

**Issue by CThuleHansen** [SamDecrock/node-http-ntlm#27]
Hi.

When using httpntlm I get the following error message:
"In order to perform this operation a successful bind must be completed on the connection".

It seems like it initiates the correct connection, gets logged in (as someuser) but somehow loses it underway. I am trying to change the password of a user (chpw) and this is my request:

```
httpntlm.put({
                url: "http://localhost:60047/api/ldap/user/chpw@domainOne",
                username: "someuser,
                password: "somepassword",
                json: JSON.parse('{"password": "xxxx"  }'),
                domain: 'domainTwo',
                headers: {
                    'Connection': 'keep-alive',
                    'Origin': 'http://localhost:60047',
                    'Host': 'localhost:60047'
                }
```
It works when I run chrome as someuser and invoke the exact same API method with the exact same arguments. 

Full exception text:
00004DC: LdapErr: DSID-0C09072B, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580

**Comment by SamDecrock** [comment]
Are you keeping track of your cookies?

**Comment by CThuleHansen** [comment]
I can not remember this issue, and I do not work at that company anymore. Cheers
