### ISSUE TITLE
status code :  401

### ISSUE THREAD

**Issue by sivadas** [SamDecrock/node-http-ntlm#30]
Getting status code as '401', though using correct username/password. below is my code:

```javascript
    httpntlm.get({
        url: "https://asnp1590a.tsg.ge.com/pc/departments/mkt/Documents for Distribution/Technical Bulletins - Catalog - Other Brochures/02 Time-Saving Wellheads - 2 Wellhead Systems/04-0394 rev 2 SH2 Split Speedhead System TB.pdf",
        username: 'lg443827sv',
        password: 'Wellhead12@Test',
        workstation: '',
        domain: '',
        timeout: 180000,
        binary: true,
        headers:{
            'Connection' : 'keep-alive'
        }
    }, function (err, res){
        if(err) {
            console.log('Error occurred : \n',err)
            return err;
        }

        console.log('headers : ', res.headers)
        console.log('status code : ', res.statusCode)
        console.log('body : ', res.body)
    });
```

Getting output as: 
```
headers :  { server: 'Microsoft-IIS/7.5',
  sprequestguid: '50291f63-72b7-4430-86c9-4be7f32b0faf',
  'www-authenticate': 'NTLM',
  'x-powered-by': 'ASP.NET',
  microsoftsharepointteamservices: '14.0.0.6120',
  'x-ms-invokeapp': '1; RequireReadOnly',
  date: 'Wed, 09 Sep 2015 06:22:22 GMT',
  'content-length': '0' }
status code :  401
body :  <Buffer >
```

Not sure, if I'm missing anything.

Thanks,
Siva

**Comment by s-KaiNet** [comment]
Same error, the case is that you updated node to >= 4.0.0.0 version....
Looking into how to fix that.

**Comment by s-KaiNet** [comment]
Disregard my previous comment. In order to make it work you need to specify valid domain or workstation.

**Comment by spacattac** [comment]
i have this same 'unauthorized' problem if npm async module is v1.*
works fine up through v0.9.2
i'm in a windows environment and use npm flatten to flatten the node_modules - a different module is loading async 1.4.2 and kaboom! 
if i at least keep a lower version of asyn local to httpntlm it works.

**Comment by spacattac** [comment]
when using async v0.9.2 and lower i have the workstation and domain set to '' and it works.  i've tried different entries in domain and workstation and still fail if async is 1.4.2

**Comment by jeme** [comment]
Having the same issue with a provided domain.
Downgrading async as @spacattac doesn't seem to have any impact, Node is  v4.2.1.
Will test with older Node versions
