### ISSUE TITLE
Unable to see traffic in Fiddler

### ISSUE THREAD

**Issue by parthsha** [SamDecrock/node-http-ntlm#43]
Hi,

I was wondering if it is possible to view the traffic generated by this package in Fiddler. I keep getting "www-authenticate not found on response of second request" error, but if I go to the URL manually, I don't see that issue. I wanted to see what is the response this module is getting and would prefer doing so without modifying the code.

Thanks.

**Comment by SamDecrock** [comment]
Normally you should see it. When I was writing this module, I used Fiddler to figure out how my browser did the NTLM-authentication.

Can you post an image of what you see in Fiddler?

**Comment by parthsha** [comment]
I can post an image in Fiddler but it will be of no use. I don't see a single entry from the moment I launch my tests.

**Comment by SamDecrock** [comment]
You could use Wireshark instead.

Fiddler only works if you can set a proxy.

2016-08-10 19:25 GMT+02:00 Parth Shah <notifications@github.com>:

**Comment by parthsha** [comment]
Thank you for your recommendation Sam! I had an initial suspicion (and now confirmed) that there may be some DNS related issue with the URL which I was passing. In my case, my URL was not fully qualified (i.e. only had machine name in it) and only after I changed it to fully qualified (i.e. machine name + domain name), things were running as expected. I still am not sure what response (if not error) httpntlm was getting using the old URL. 

I am trying to find a workaround so that I can use my old URL instead of the fully qualified one. The reason why I want to use my old URL is so that I don't get authentication dialog appearing in Chrome. When I use the fully qualified URL in Chrome, I get prompted to enter username/password, which is both annoying and hard to get around from testing perspective.

**Comment by parthsha** [comment]
I have found a way to unblock myself. Thank you for your help Sam.
