### ISSUE TITLE
Refuses to work if domain and/or workstation is "" in node 6.4.0

### ISSUE THREAD

**Issue by Suppen** [SamDecrock/node-http-ntlm#46]
I upgraded from node 6.3.1 to 6.4.0, and my application broke. The specific line on which it broke is 97 in ntlm.js

The problem is that the variable `pos`, holding the buffer offset is 40, which is also the length of the buffer. When trying to `buf.write` the workstation and domain names, both "" (empty string), the method throws a `RangeError` because the offset points to the byte after the end of the array.

My temporary fix is to comment out the lines writing workstation and domain to the buffer, but that is not a general solution

**Comment by Suppen** [comment]
This works again in Node 6.5.0

**Comment by SamDecrock** [comment]
Let me know if it's fixed.

**Comment by Suppen** [comment]
Not using Node 6.4.0 anymore, but judging by your commit, it should be fixed

**Comment by SamDecrock** [comment]
All right, good :)
