### ISSUE TITLE
httpntlm stopped working for me

### ISSUE THREAD

**Issue by arieljannai** [SamDecrock/node-http-ntlm#49]
Hi,

Somewhere in the last few days it stopped working for me.
I'm using _httpntlm_ to access a server that uses [nodesspi](https://github.com/abbr/NodeSSPI) for authentication, and until now it worked great.
The server still works if I'm accessing it directly or from another method  (curl & browser), but returns `Login aborted` for the _httpntlm_ requests (both GET and POST).

I didn't made any changes in the code, and I see that also this module or its dependencies weren't updated lately.

Maybe you have an idea on why it might happen?
Any advice on what to check?

Thanks!

**Comment by SamDecrock** [comment]
Could you post errors or anything you're getting back from the server?

It's kinda hard for me to test this module as I don't have an NTLM-service
anymore.

2016-09-07 13:43 GMT+02:00 Ariel Jannai <notifications@github.com>:

**Comment by arieljannai** [comment]
From the node-sspi based server, I'm getting [`Login aborted`](https://github.com/abbr/NodeSSPI/blob/d539c9004156116c935d6cbee04faab1afd34020/src/NodeSSPI.cpp#L463) with status code 401 - unauthorized.

When debugging a bit, I see that my server does not get any user (just `undefined`) so it doesn't have any user to try to authenticate.

From http-ntlm side, I saw that the request is sent with authorization headers (the `NTLM xyz` and `www-authenticate`) and fails in the first variation and also in the second. I dig a bit further inside and I also haven't encountered anything weird or alarming in the httpreq and http (I stopped over there).

**Comment by SamDecrock** [comment]
Hi,

Have you found anymore clues as to why it fails?

Did you switch between 2 versions perhaps?

Sam

**Comment by arieljannai** [comment]
Unfortunately I couldn't find anything, so I had to solve it with other ways (just used `curl` command, it was the fastest fix at the moment).
I'm also not at that work place anymore, so I can't check it again to help with figuring it out
