### ISSUE TITLE
example for client-side usage?

### ISSUE THREAD

**Issue by ferdiozturk** [SamDecrock/node-http-ntlm#56]
Is httpntlm tested for browser client-side use? I want to impersonate another user (service account) from within an already NTLM authenticated web client. Because the authenticated connection is already there I had to open a new connection to the same URL with different port to have a new connection. Is there an easier way or am I missing sth? I've used webpack to have the needed nodejs modules on client-side

**Comment by SamDecrock** [comment]
On a browser, NTLM-authentication is implemented by the browser itself. Chrome, Firefox, IE, they implemented this.

This module also implements the NTLM-authentication so you can use in other (not-browser) places too. If you can write custom headers with AJAX-requests, then you could theoretically use this in the browser too.

In your case, if the browser is already authenticated, then there's no need to authenticate again. You can just do what you need to do from within that browser session.

**Comment by ferdiozturk** [comment]
the pre-auth user in the browser is unprivileged on the connected-to Microsoft Team Foundation Server, I'm trying to create a web page that impersonats to a pre-defined service account which has permissions to call specific REST apis on TFS, not with the pre-auth user but the admin-like service account

**Comment by SamDecrock** [comment]
Then I'll think you'll be better of using a Node.js server in between. Where the Node.js server connects to the Microsoft server and you connect to the Node.js

I think the moment you'll try to connect to the Microsoft server, the browser will do the authentication. There's no way to force the browser to "not do" the authentication.

**Comment by spyshow** [comment]
sorry to reopen the issue but i have the same problem 
i'm writing an electron app ( which a magic mix of chrome and node.js) ... i'm trying to connect to TFS server but couldn't through normal ajax call .... can i use this module to call  a REST API of TFS ? can you give a small example ? 

thanks

**Comment by mlembke1** [comment]
Hey @SamDecrock, I understand that you have mentioned that the browsers do this already. However, that is only true if you are hitting the endpoint from the browser. There are cases where an application is running in the browser, and that application sends out a request. In this case, the request isn't actually coming from the browser itself, but from the application that is running in the browser is sending the request. 

I think this is where the use case comes in. Can we assume that this module will work using client side JavaScript as well? Thanks in advance!
