### ISSUE TITLE
Storing Cookies & Keeping Session Alive

### ISSUE THREAD

**Issue by shanewignall** [SamDecrock/node-http-ntlm#58]
This module seems to be properly going through the NTLM handshake, but I'm unsure of how to store the site's authentication cookie and keep the session alive to actually interact with the website. 

Perhaps I just don't understand the intended workflow in which to incorporate this module into.  What I want to do:
1. Authenticate with website
2. Save a security cookie generated upon handshake completion for future requests
3. Make requests with request (https://github.com/request/request) using the cookie

Am I going about it the wrong way?

**Comment by SamDecrock** [comment]
I fear that every request needs to contain some kind of NTLM handshake, I'm not sure.

**Comment by shanewignall** [comment]
A log-in request in an actual browser produces an ASP.NET_SessionId cookie. Would I be incorrect in assuming that I should be able to store that cookie after authentication to use in subsequent requests within the same session?

If so.. is it possible to pull that cookie information with node-http-ntlm?

**Comment by SamDecrock** [comment]
sure, cookies are stored in the res-object.
It could be that ASP.NET also uses some kind of viewstate POST-variable that you need to pass on, I'm not sure.

**Comment by shanewignall** [comment]
Ah, I think the reason I was confused was because the cookie is being generated in a different request than the one I've been looking with.

Thanks for the help - love this module!

**Comment by revolunet** [comment]
Hi @shanewignall, did you find a way to reuse the cookie provided by http-ntlm ?

**Comment by shanewignall** [comment]
@revolunet No, I wasn't able to figure that out.. I ended up not needing to perform this task. Sorry!

**Comment by revolunet** [comment]
Thanks for answering !
