### ISSUE TITLE
Supports only NTLMv1? or supports NTLMv2 as well?

### ISSUE THREAD

**Issue by raghuureddy** [SamDecrock/node-http-ntlm#59]
Hello Sam,

My SharePoint site uses NTLMv2 & on the IIS server 'lmcompatibilitylevel' registry is set as '5'.

This module supports only NTLMv1? I see that in the code the naming convention is as below.

`create_LM_hashed_password_v1`

Wondering if this only supports NTLMv1.

I am getting always 401 Unauthorized from SharePoint site & its passing all handshake including type3 message. But the response comes as 401.

**Comment by SamDecrock** [comment]
I suppose it doesn't.
If you can provide me with the protocol for v2, I can have a look at it and implement... if I find the time.

**Comment by istersin** [comment]
I can confirm that this does not work with NTLM v2. This project seems to support v2, but it is not working for me for some reason. I just started looking into the code, and if get it working I'll follow up here, on what can be done to support NTLM v2.

**Comment by istersin** [comment]
No progress on this one. Seems there is no js library to handle NTLM v2 support. @raghuureddy Have you made any progress? @SamDecrock Any ideas on this one?

**Comment by SamDecrock** [comment]
Do you know what server side applications/services use NTLM v2 so I can set
up one myself and check it out?


2017-02-20 10:46 GMT+01:00 vertigo <notifications@github.com>:

**Comment by s-KaiNet** [comment]
Hi Sam,   
please take a look at this [comment here](https://github.com/koltyakov/sppull/issues/13#issuecomment-272631004)  
As far as I understand all you need is to change reg value to `2` or something bigger than `2` (less than `6`)

**Comment by Simran-B** [comment]
So the solution is to change the registry key `HKLM\SYSTEM\CurrentControlSet\Control\Lsa\LmCompatibilityLevel` to `5`?

https://technet.microsoft.com/en-us/library/cc960646.aspx

@raghuureddy @emcho92  Can you test this?

**Comment by Dror-Bar** [comment]
Any update on this?

**Comment by s-KaiNet** [comment]
@Dror-Bar I use [this one](https://github.com/gautamsi/node-ntlm-client) ([npm](https://www.npmjs.com/package/node-ntlm-client)) which works very well for both ntlm v1 and v2. I migrated from `httpntlm` like 6 months ago, no issues so far.

**Comment by Dror-Bar** [comment]
Thanks.
I wish there were some real example usage, but I'll definitely check it out!

**Comment by s-KaiNet** [comment]
I use it in my own module, so you can dig into the file [OnpremiseUserCredentials.ts](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/resolvers/OnpremiseUserCredentials.ts) for a real usage example.    

The class itself performs NTLM auth and returns credentials via `Authorization` header. You can attach that header to your ongoing http request against NTLM protected resource. keep alive agent also seems required.

**Comment by Dror-Bar** [comment]
@s-KaiNet 
Sorry for the late response. Great! Thanks a lot. Could you perhaps help a beginner like me? I'm trying to create a simplified version, not sure if I'm doing it right. Will something like this work?

Before:
```
httpntlm.get(
            {
                url: URL,
                username: USERNAME,
                password: PASSWORD,
                domain: DOMAIN,
                ca: ca
            },
                function (err, res) {
                    if (err) console.log(err);
                    else console.log(res);
           });
```
After?
```
request(
            {
                url: URL,
                headers: { 'Authorization': type1msg },
                agent: keepaliveAgent,
                ca: ca
            },
                function (err, res) {
                    if (err) console.log(err);
                    const type2msg = ntlm.decodeType2Message(res.headers['www-authenticate']);
                    const type3msg = ntlm.createType3Message(type2msg, USERNAME, PASSWORD);
           });
```
Then I'm a bit lost. How should I continue from here?
or is this all wrong?

**Comment by pano9000** [comment]
I guess seeing that https://github.com/SamDecrock/node-http-ntlm/commit/ca31baf93451ad387dbb84b4f8642eb9aa380a1f , which adds NTLMv2 support, has been merged, this topic can potentially be closed?

**Comment by SamDecrock** [comment]
Indeed. Thanks for the heads up.
