### ISSUE TITLE
pass along other options

### ISSUE THREAD

**Issue by NAlexandrov** [SamDecrock/node-http-ntlm#61]
Add a next code to sendType1Message function, please:

```javascript
// pass along other options:
type1options.headers = _.extend(type1options.headers, httpreqOptions.headers);
type1options = _.extend(type1options, _.omit(httpreqOptions, 'headers'));
```

Without this code can not be added rejectUnauthorized in request options

**Comment by matiasdelgado** [comment]
It used to be exactly as @NAlexandrov suggests, but it was changed in this commit [36e9ad0](https://github.com/SamDecrock/node-http-ntlm/commit/36e9ad00127c7a023089aef64bf352ee66768bd4). Not sure why the options where limited to just `timeout` and `ca`, leaving the `proxy` and other options out. Any thoughts?

**Comment by SamDecrock** [comment]
Merged this PR. Thanks a lot!
