### ISSUE TITLE
ReferenceError: callback is not defined return callback(new Error('www-authenticate not found on response of second request'));

### ISSUE THREAD

**Issue by Nightwelf** [SamDecrock/node-http-ntlm#63]
node_modules/sharepointconnector/lib/auth/ntlm.js:32
        return callback(new Error('www-authenticate not found on response of second request'));
               ^

ReferenceError: callback is not defined
    at node_modules/sharepointconnector/lib/auth/ntlm.js:32:16
    at fn (node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by SamDecrock** [comment]
Can you show me part of your code where you're making the ntlm call?

**Comment by Nightwelf** [comment]
I use cyrillic in sharepointconnector. It is not my project, it is using your project.

**Comment by SamDecrock** [comment]
Problem is that if you are not defining a callback in your code, my code will complain ;-)

**Comment by SamDecrock** [comment]
Please file the bug at sharepointconnector
