### ISSUE TITLE
[Suggestion] Implement doRequest.

### ISSUE THREAD

**Issue by SPWizard01** [SamDecrock/node-http-ntlm#65]
Great library!
But, for power users after taking a quick look(not sure how involved this is) something like this worked:
[https://github.com/SamDecrock/node-http-ntlm/blob/master/httpntlm.js#L107-L109](url)
to
`['get', 'put', 'patch', 'post', 'delete', 'options', 'doRequest'].forEach(function(method){
	exports[method] = exports.method.bind(exports, method);
});`

and

[https://github.com/SamDecrock/node-http-ntlm/blob/master/httpntlm.js#L93-L94](url)
to
`if(method !== 'doRequest') {
	httpreq[method](options.url, type3options, callback);
}
else {
	type3options.url = options.url;
	httpreq[method](type3options, callback);
}`

**Comment by SamDecrock** [comment]
Is there more to HTTP than 'get', 'put', 'patch', 'post', 'delete', 'options' ?
