### ISSUE TITLE
Allow passing in an http agent.

### ISSUE THREAD

**Issue by lucyluu22** [SamDecrock/node-http-ntlm#66]
Correct me if I'm wrong, but wouldn't re-using a http agent instead of creating a new one every request mean you'd only need to do do the handshake once on the same server (since the connection would be persisted)?

May also help issue #5

**Comment by SamDecrock** [comment]
The `keepaliveAgent` is only created once and then re-used for all messages.

**Comment by SamDecrock** [comment]
Added the option in version 1.8.9

Eg
```js
var httpntlm = require('httpntlm');
var http = require('http');

var myKeepaliveAgent = new http.Agent({keepAlive: true});

httpntlm.get({
  url: "http://localhost:3000",
  username: 'm$',
  password: 'stinks',
  workstation: 'choose.something',
  domain: 'somedomain',
  agent: myKeepaliveAgent
}, function (err, res){
  if(err) return console.log(err);

  console.log(res.headers);
  console.log(res.body);
});
```
