### ISSUE TITLE
Breaks from node v6.7.0 to v6.8.0

### ISSUE THREAD

**Issue by chris-erickson** [SamDecrock/node-http-ntlm#70]
v6.7.0 is the last version of node that works for this library.  When we run under v6.8.0 we get 401 Unathorized with everything else otherwise unchanged.

Where do I even begin debugging this?  The parameters (`opts`) provided to 
```javascript
httpntlm.get(opts, function (err, resp) {
	handleProxyResponse(res, err, resp);
});
```
are the same under both versions, so it appears that some functionality of the ntlm lib has changed during this transition.  Any help is appreciated.

**Comment by SamDecrock** [comment]
Closing issue as the minimum node.js version is now 10.4.0.
