### ISSUE TITLE
Couldn't find NTLM in the message type2 comming from the server

### ISSUE THREAD

**Issue by tksdia** [SamDecrock/node-http-ntlm#78]
Most times it works but some times failed with below error. 

Couldn't find NTLM in the message type2 comming from the server\n    at Object.parseType2Message (....\\node_modules\\httpntlm\\ntlm.js:116:12)\n    at sendType3Message (C:\\node_soa\\soa.referencedata.service\\node_modules\\httpntlm\\httpntlm.js:73:23)\n    at Immediate.<anonymous> (....\\node_modules\\httpntlm\\httpntlm.js:101:4)\n    at runCallback (timers.js:666:20)\n    at tryOnImmediate (timers.js:639:5)\n    at processImmediate [as _immediateCallback] (timers.js:611:5)

my code is making an http api call which is protected by windows auth.

httpntlm.get(
                {
                    url,
                    username,
                    password,
                    workstation,
                    domain:"XXX"
}
Thanks a lot.

**Comment by hari319** [comment]
any update please??

**Comment by UmerIftikhar** [comment]
@SamDecrock  Any Update on this?

**Comment by ragorepo** [comment]
Me too facing this issue at regular intervals - but there is no clear root cause at our end. 
Any update or if any one get through this please help..

**Comment by rp21buzz** [comment]
This issue is a result of source not responding to the request due to some kind of outage like

there is a bottle neck at the target end's network traffic,
or the source config isn't able to reach the target for connections.

nothing to do with the library.

**Comment by glorianak** [comment]
if your working with NAV/Business central,
In NAV or Business Central Administration, there is a field in the General tab called Use NTLM Authentication ensure that it is checked (set to true).  it helped me resolve this issue
