### ISSUE TITLE
Can't post to specific host 

### ISSUE THREAD

**Issue by AmitBaranes** [SamDecrock/node-http-ntlm#80]
Hey,
when trying to post to a specific machine getting 401.

Example : 
  const url = `https://MACHINENAME.DOMAIN.COM/exampleService.svc`; 

response body :
```
<h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
<h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
```
this is weird since i do see the NTLM Authorization header.

when i was trying to post to the URL without the server name in the URL , I was able to get 200 from to server.

Example :

const url = `https://exampleService.com/exampleService.svc`;

Please advise.
Thanks,
Amit.

**Comment by nazywamsiepawel** [comment]
+1

**Comment by SamDecrock** [comment]
Make sure `MACHINENAME.DOMAIN.COM` is resolvable. I'm closing this ticket for now. Reopen it if you want to.
