### ISSUE TITLE
Unable to resolve module `http` could not be found

### ISSUE THREAD

**Issue by sammuri09** [SamDecrock/node-http-ntlm#90]
Unable to resolve module `http` from `node_modules\httpntlm\httpntlm.js`: http could not be found within the project.

**Comment by sammuri09** [comment]
not found url, http, https, fs, crypto because they now built-in to node, how to solve this please someone help me

**Comment by SamDecrock** [comment]
Which version of node.js are you using?

**Comment by SamDecrock** [comment]
I get the feeling you are using React Native. This module was made for node.js
