### ISSUE TITLE
Black duck scanner not allowing Underscore package.

### ISSUE THREAD

**Issue by kunalkagalkar** [SamDecrock/node-http-ntlm#95]
Hi Team,
We have used Soap package for our recent projects and Soap has httpntlm->underscore@1.7.0 dependency.
Its getting restricted by black duck static scanner. Could you please update underscore package?
Its halted our production.
Please help.

**Comment by RopoMen** [comment]
Currently npm audit also fails due https://www.npmjs.com/advisories/1674

> "soap>httpntlm>underscore"

**Comment by RopoMen** [comment]
https://github.com/SamDecrock/node-http-ntlm/pull/93
