### ISSUE TITLE
Updating the underscore npm used in node-http-ntlm version

### ISSUE THREAD

**Issue by tas-null** [SamDecrock/node-http-ntlm#97]
the latest version of https://www.npmjs.com/package/httpntlm bundles a vulnerable version of underscore@1.7.0 which has a security advisory attached to it as per npm audit. Can you please also update the dependencies used in httpntlm allowing secure usage of your npm.

Thanks for everything!

**Comment by SamDecrock** [comment]
Fixed and merged https://github.com/SamDecrock/node-http-ntlm/pull/93
