### ISSUE TITLE
Type 3 response always sends Unicode flag even if server did not request it in the type 2 message

### ISSUE THREAD

**Issue by DavidTheWin** [SamDecrock/node-http-ntlm#98]
I'm using this library to talk to an expressjs server using the express-ntlm library to handle the server side of the NTLM auth.
When ntlm.js parses the type 2 message and starts creating the type 3 message, the `isUnicode` flag is `0` so the workstation, domain, and username are written in ascii.
However, line 228 writes `typeflags.NTLM_TYPE2_FLAGS` to the flags position in the buffer, which always sets the Unicode flag. This means that when express-ntlm receives the data, it sees the unicode flag and tries to parse the workstation, domain, and username in Unicode which does not match the ascii input that ntlm.js originally wrote to the buffer.

Doing the below, to take out the unicode flag if it was not requested by the server works as expected.
```javascript
var flagsToWrite = isUnicode
    ? typeflags.NTLM_TYPE2_FLAGS
    : typeflags.NTLM_TYPE2_FLAGS - flags.NTLM_NegotiateUnicode;
buf.writeUInt32LE(flagsToWrite , pos); pos += 4; // NegotiateFlags
```

The underlying problem here is that express-ntlm doesn't seem to respect the unicode flag that httpntlm sends in its type 1 message, but that doesn't mean that this library should send back a contradictory type 3 message.

**Comment by SamDecrock** [comment]
Ok, that makes sense. I fixed it in the code using your code snippet: https://github.com/SamDecrock/node-http-ntlm/commit/efc76ab2333bb2528a79e86c5bdc54e9d6a32f8f It's not in version 1.8.7
